# Generated by Django 3.2.8 on 2021-12-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211202_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='category',
            new_name='categories',
        ),
    ]
